### ISSUE TITLE
主动调用任意函数报错

### ISSUE THREAD

**Issue by ihbing** [monkeylord/XServer#13]
```java
08-12 10:22:14.686 8637-9212/? W/System.err: java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
        at libcore.io.IoBridge.sendto(IoBridge.java:511)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
08-12 10:22:14.687 8637-9212/? W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
        at java.io.OutputStream.write(OutputStream.java:82)
        at libcore.io.Streams.writeSingleByte(Streams.java:53)
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:262)
        at monkeylord.XServer.utils.NanoWSD$WebSocketFrame.write(NanoWSD.java:702)
        at monkeylord.XServer.utils.NanoWSD$WebSocket.sendFrame(NanoWSD.java:390)
        at monkeylord.XServer.utils.NanoWSD$WebSocket.send(NanoWSD.java:385)
        at monkeylord.XServer.api.wsMethodViewNew$ws.trySend(wsMethodViewNew.java:61)
        at monkeylord.XServer.api.wsMethodViewNew$MethodHook.beforeHookedMethod(wsMethodViewNew.java:128)
        at monkeylord.XServer.XposedEntry$1$1.beforeHookedMethod(XposedEntry.java:91)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
        at com.mywickr.util.RootUtils.isRooted(<Xposed>)
        at java.lang.reflect.Method.invoke(Native Method)
        at monkeylord.XServer.api.Invoke.handle(Invoke.java:27)
        at monkeylord.XServer.api.BaseOperation.handle(BaseOperation.java:22)
        at monkeylord.XServer.XServer.serveHttp(XServer.java:128)
        at monkeylord.XServer.utils.NanoWSD.serve(NanoWSD.java:164)
        at monkeylord.XServer.utils.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:1973)
        at monkeylord.XServer.utils.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:1522)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: sendto failed: EBADF (Bad file descriptor)
        at libcore.io.Posix.sendtoBytes(Native Method)
        at libcore.io.Posix.sendto(Posix.java:211)
        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
        at libcore.io.IoBridge.sendto(IoBridge.java:509)
    	... 22 more
08-12 10:22:14.689 8637-9212/? E/[XServer Debug]: result: null
08-12 10:22:14.690 8637-9212/? W/System.err: java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
        at libcore.io.IoBridge.sendto(IoBridge.java:511)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
        at java.io.OutputStream.write(OutputStream.java:82)
        at libcore.io.Streams.writeSingleByte(Streams.java:53)
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:262)
        at monkeylord.XServer.utils.NanoWSD$WebSocketFrame.write(NanoWSD.java:702)
        at monkeylord.XServer.utils.NanoWSD$WebSocket.sendFrame(NanoWSD.java:390)
        at monkeylord.XServer.utils.NanoWSD$WebSocket.send(NanoWSD.java:385)
        at monkeylord.XServer.api.wsMethodViewNew$ws.trySend(wsMethodViewNew.java:61)
08-12 10:22:14.691 8637-9212/? W/System.err:     at monkeylord.XServer.api.wsMethodViewNew$MethodHook.afterHookedMethod(wsMethodViewNew.java:171)
        at monkeylord.XServer.XposedEntry$1$1.afterHookedMethod(XposedEntry.java:107)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
        at com.mywickr.util.RootUtils.isRooted(<Xposed>)
        at java.lang.reflect.Method.invoke(Native Method)
        at monkeylord.XServer.api.Invoke.handle(Invoke.java:27)
        at monkeylord.XServer.api.BaseOperation.handle(BaseOperation.java:22)
        at monkeylord.XServer.XServer.serveHttp(XServer.java:128)
        at monkeylord.XServer.utils.NanoWSD.serve(NanoWSD.java:164)
        at monkeylord.XServer.utils.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:1973)
        at monkeylord.XServer.utils.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:1522)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: sendto failed: EBADF (Bad file descriptor)
        at libcore.io.Posix.sendtoBytes(Native Method)
        at libcore.io.Posix.sendto(Posix.java:211)
        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
        at libcore.io.IoBridge.sendto(IoBridge.java:509)
    	... 22 more

```

**Comment by monkeylord** [comment]
这个调用方式目前不在维护中。
推荐使用Burp来进行调用。
你在这个查看方法界面的时候，方法被访问时，你的抓包工具是可以抓到 /invoke2 报文的。
那个报文和响应就是方法的调用和返回。

那个报文是可以使用重放、爆破等等的方式的，实现主动调用。

**Comment by monkeylord** [comment]
你这个问题应该是方法页面关了，所以WebSocket连接出错。

如果你就是想要这种方法调用的话，你保留那个调用结果的页面，再启动应用时不要进方法页面，而是直接刷新那个调用结果。

**Comment by monkeylord** [comment]
或者你开上代理应该也行。
我一般的代理设置是Burp监听在8080
然后
adb shell settings put global http_proxy 127.0.0.1:8080
adb reverse tcp:8080 tcp:8080

**Comment by ihbing** [comment]
好的，我试试
