### ISSUE TITLE
8000 端口打不开，xposed 模块日志有报错

### ISSUE THREAD

**Issue by sheng-di** [monkeylord/XServer#26]
网页未发送数据：
![image](https://user-images.githubusercontent.com/13643746/151668092-952165ad-e7f3-46f7-a749-35d0b5fa4feb.png)
查看模块日志发现：
```
[ 2022-01-30T00:04:09.750        0:   684:  1348 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-01-30T00:04:09.75.log
[ 2022-01-30T00:04:29.258    10350: 19640: 19640 I/LSPosed         ] Loading modules for com.example.buttontoast/10350
[ 2022-01-30T00:04:29.260    10350: 19640: 19640 I/LSPosed-Bridge  ] Loading module monkeylord.xserver from /data/app/monkeylord.xserver-1f9k9skhlD_6N4v1ahiAuw==/base.apk
[ 2022-01-30T00:04:29.341    10350: 19640: 19640 I/LSPosed-Bridge  ]   Loading class monkeylord.XServer.XposedEntry
[ 2022-01-30T00:04:29.567    10350: 19640: 19640 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object reference
	at com.blankj.utilcode.util.NetworkUtils.getIPAddress(NetworkUtils.java:515)
	at monkeylord.XServer.XposedEntry.handleLoadPackage(XposedEntry.java:105)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at D1.afterHookedMethod(Unknown Source:111)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1034)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5874)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1200(ActivityThread.java:206)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1686)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6882)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by monkeylord** [comment]
应该是该应用没有Internet权限所致。
可以先允许Internet权限再试试。
